title: Jongwon
email: lastone9182@gmail.compressed
github_username: lastone9182

theme: minima

markdown: kramdown

collections:
  - my_database
  - my_codingthematrix


defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: my_database
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: my_codingthematrix
    values:
      layout: "post"


collections:
  my_database:
    output: true
  my_codingthematrix:
    output: true


sass:
 sass_dir: _sass
 style: compressed
