title: LemonBerry


markdown: redcarpet
redcarpet:
  extensions: [
    "tables",
    "footnotes",
    "underline",
    "autolink",
    "strikethrough",
    "space_after_headers",
    "with_toc_data",
    "fenced_code_blocks"
  ]

collections:
  - my_database
  - my_codingthematrix


defaults:
  -
    scope:
      path: ""
      type: my_database
    values:
      layout: post
  -
    scope:
      path: ""
      type: my_codingthematrix
    values:
      layout: post
  -
    scope:
      path: ""
      type: my_profile
    values:
      layout: post


collections:
  my_database:
    output: true
  my_codingthematrix:
    output: true
  my_profile:
    output: true


sass:
 sass_dir: _sass
 style: compressed


paginate: 5
paginate_path: "/page:num/"
