title: LemonBerry


markdown: kramdown


collections:
  - my_database


defaults:
  -
    scope:
      path: ""
      type: my_database
    values:
      layout: post


collections:
  database:
    output: true


sass:
 sass_dir: _sass
 style: compressed
