title: LemonBerry


markdown: redcarpet
markdown_ext: markdown,mkdown,mkdn,mkd,md

redcarpet:
  extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "with_toc_data", "fenced_code_blocks"]

collections:
  - my_database
  - my_codingthematrix


defaults:
  -
    scope:
      path: ""
      type: my_database
    values:
      layout: post
  -
    scope:
      path: ""
      type: my_codingthematrix
    values:
      layout: post


collections:
  my_database:
    output: true
  my_codingthematrix:
    output: true


sass:
 sass_dir: _sass
 style: compressed


paginate: 5
paginate_path: "/page:num/"
