title: LemonBerry


markdown: kramdown


collections:
  - database


defaults:
  -
    scope:
      path:"docs/database"
      type:"database"
    values:
      layout: post


collections:
  database:
    output: true


sass:
 sass_dir: _sass
 style: compressed
