title: Jongwon
email: lastone9182@gmail.com
github_username: lastone9182


# New variable
progress: true



theme: minima
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Rouge Options › https://github.com/jneen/rouge#full-options
    css_class: 'highlight'
    #line_numbers: true # bad idea, spans don't need linenos and would inherit this option
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1


collections:
  - my_database
  - my_codingthematrix


defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: my_database
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: my_codingthematrix
    values:
      layout: "post"


collections:
  my_database:
    output: true
  my_codingthematrix:
    output: true


sass:
 sass_dir: _sass
 style: compressed
