title: LemonBerry


markdown: kramdown


collections:
  - my_database


defaults:
  -
    scope:
      path: ""
      type: my_database
    values:
      layout: post


collections:
  my_database:
    output: true


sass:
 sass_dir: _sass
 style: compressed


paginate: 3
paginate_path: "/page:num/"
