rem
rem	Script:		pat_dump.sql
rem	Author:		Jonathan Lewis
rem	Dated:		Sep 2004
rem	Purpose:	Example for "Cost Based Oracle"
rem
rem	Last tested:
rem		10.1.0.4
rem		 9.2.0.6
rem	Not relevant
rem		 8.1.7.4
rem
rem	Called from a script generated by either
rem	pat_nocpu_harness.sql or pat_cpu_harness.sql
rem


alter session set events '10053 trace name context forever, level 2';
alter session set events '10104 trace name context forever';

alter system set pga_aggregate_target = &2 scope = memory;
alter session set tracefile_identifier = 'pat_&1._&2';

select
	/*+
		ordered use_hash(pb) full(pb) full(bu) &2
	*/
	bu.build_vc,
	bu.build_padding,
	pb.probe_vc,
	pb.probe_padding
from
	test_user.build_tab	bu,
	test_user.probe_tab	pb
where
	bu.id between 1 and 2000
and	pb.id = bu.id_probe
;




alter session set events '10053 trace name context off';
alter session set events '10104 trace name context off';
