title: Jongwon
email: lastone9182@gmail.com
github_username: lastone9182


# New variable
progress: true


markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Rouge Options › https://github.com/jneen/rouge#full-options
    css_class: 'highlight'
    #line_numbers: true # bad idea, spans don't need linenos and would inherit this option
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1


defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "default"


sass:
 sass_dir: _sass
 style: compressed
